sudo: required

language: node

services:
  - docker

branches:
  only:
  - demo

jobs:
  include:
    - stage: MOM-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mom_frontend_flowz:demo --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" ./client/
      - docker images
      - docker tag mom_frontend_flowz:demo $DOCKER_USERNAME/mom_frontend_flowz:demo
      - docker push $DOCKER_USERNAME/mom_frontend_flowz:demo
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - uhirani@officebrain.com
      - igandhi@officebrain.com
    on_success: always
    on_failure: always
